// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_read_sndfile
Rcpp::List cpp_read_sndfile(const char * fname, int from, int to, bool metadata);
RcppExport SEXP _wavr_cpp_read_sndfile(SEXP fnameSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< bool >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_read_sndfile(fname, from, to, metadata));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wavr_cpp_read_sndfile", (DL_FUNC) &_wavr_cpp_read_sndfile, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_wavr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
