# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_read_sndfile <- function(fname, from = 1L, to = 2147483645L, metadata = TRUE) {
    .Call(`_wavr_cpp_read_sndfile`, fname, from, to, metadata)
}

